
- stat: path=/var/lib/docker
  register: docker_data_orig

- name: Create docker data directory
  when: not docker_data_orig.stat.isdir
  file:
    path: /mnt/data/docker
    owner: root
    group: root
    state: directory
    mode: 0700
    recurse: true # /mnt/data may not exists

- name: Store docker files in data disk
  when: not docker_data_orig.stat.isdir
  file:
    src: /mnt/data/docker
    dest: /var/lib/docker
    state: link

- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present

- name: linux-image-extra is present
  apt:
    name: linux-image-extra-{{ ansible_kernel }}

- name: docker-engine is present
  apt:
    name: docker-engine
    state: latest
    force: yes

- name: Debian python-pip is present
  apt:
    name: python-pip
    state: present

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.6.0
    state: present

- name: Debian files are present
  template:
    src: docker.cfg
    dest: /etc/default/docker
  register: copy_result

- name: User is added to the docker group
  user:
    name: "{{ user }}"
    group: docker
  register: user_result

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
