- hosts: default
  user: ubuntu
  become: true
  gather_facts: true
  vars:
    - user: ubuntu
  roles:
    - common
    - java
    - docker
    - docker-compose
    - registry
    - node
    - cje
    - users
    - { role: preload, when: "preload is defined" }
